### ISSUE TITLE
send to new pane instead of current

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/atom-unix-filter#2]
Could you please tell what should be modified to send output to new pane with unsaved file instead of changing current text?

**Comment by lierdakil** [comment]
Open a new editor in a new pane via `atom.workspace.open('', {split: ...})`, which returns a `Promise<TextEditor>`, and `setText` on that one?

**Comment by kiwi0fruit** [comment]
Thanks. I guess I'll try this later. For now I went with easier tweaks.
